# Generated by Django 3.2.5 on 2021-09-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isOutOfStock',
            field=models.BooleanField(default=False),
        ),
    ]
